### ISSUE TITLE
Theme main color pallets not fully displayed

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/hipstyle#1]
The color pallets for the following options in the theme will not fully display:
Theme Color: https://prnt.sc/v4ix5j
Box Color: https://prnt.sc/v4ixd0

**Comment by mahendrapratap4022** [comment]
Hi, It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198  hope they approve and merge it soon.
Thanks
