### ISSUE TITLE
Header color pallets not fully displaying

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/hipstyle#3]
The color pallets in the header for the following options is not fully displayed :
Other Page Header menu hover color : https://prnt.sc/v4n1fc
Dropdown menu color : https://prnt.sc/v4n307
Dropdown menu hover color : https://prnt.sc/v4n39y

**Comment by mahendrapratap4022** [comment]
Hi, It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198  hope they approve and merge it soon.
Thanks
