### ISSUE TITLE
404 error message upper letter

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/hipstyle#6]
In the preview mode for the 404 page we should have the message "404 Error" message with the upper letters like on the Shotgear Theme :
Hipstyle Theme : https://prnt.sc/v4n98r
Shotgear Theme : https://prnt.sc/uw7pfi

**Comment by mahendrapratap4022** [comment]
Hi I have added this request in https://github.com/ColorlibHQ/hipstyle/pull/9
Thanks
